import "@/app/globals.css";
import type { Metadata } from "next";
  
//TODO: construct metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning className="">
      <head/> 
        <body>
          {/* <Navbar /> */}
          {children} 
        </body> 
    </html>
  );
}
